manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-ardux
      url-base: https://github.com/arduxio
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmkfirmware
      remote: zmk-ardux
      revision: main
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
